#! /usr/bin/perl

use feature "switch";
no if $] >= 5.018, warnings => "experimental::smartmatch";

use URI::Escape;

my $currentsection = '';

my $product = 'openSUSE';
my @lines;
my $pat;
my $summary;
my @description;
my %patterns_arch;

sub translate_sel($$)
{
    my $filename = shift;
    my $pat = shift;

    print "# from $filename\n";

    open(FILE, $filename);

    while ( <FILE> )
    {
        next if ($_ =~ m/^\s*$/);
        if ( $_ =~ m/^\+(.*):/ ) { $currentsection = $1; next; }
        if ( $_ =~ m/^\-(.*):/ ) { $currentsection = ''; next; }

        if ( $_ =~ m/^=/ ) {
	  $currentsection = $_;
	  $currentsection =~ s,=(\S+):.*,\1,;
        }
        my $line = $_;
	chomp $line;

	next if ($line =~ m/#pragma online/);
	
	if ($line =~ m/^#if/) {
	  $line =~ s,^#if *,,;
	  my @archs = split(/\|\|/, $line);
	  my @narchs = ();
	  print "%ifarch ";
	  for my $arch (@archs) {
	    $arch =~ s,\s+,,g;
	    $arch =~ s,defined,,;
	    $arch =~ s,[()],,g;
	    if ($arch eq '__i386__') {
	      push(@narchs, '%ix86');
	    } elsif ($arch eq '__x86_64__') {
	      push(@narchs, 'x86_64')
	    } elsif ($arch eq '__powerpc__') {
	      push(@narchs, 'ppc')
	    } elsif ($arch eq '__powerpc64__') {
	      push(@narchs, 'ppc64')
	    } else {
	      push(@narchs, "-$arch-");
	    }
	  }
	  print join(' ', @narchs) . "\n";
	  next;
	}
	if ($line =~ m/^#endif$/) {
	  print "%endif\n";
	  next;
	}

	if ($line =~ m/^#/ || $line =~ m,^//,) {
	  $line =~ s,^//,#,;
	  print "$line\n";
	  next;
	}

        given($currentsection) {
            when (/Psg/) { print "Suggests:       $line\n"; }
            when (/Prq/) {
	      next if ($line eq "patterns-$product-$pat");
	      print "Requires:       $line\n";
	    }
            when (/Prc/) { print "Recommends:     $line\n"; }
            when (/Pcn/) { print "Conflicts:      $line\n"; }
        }

    }

    print "\n";

    close(FILE);
}

my $pat = $ARGV[0];

sub read_file($) {
  my $file = shift;

  open(FILE, $file);
  my $c = <FILE>;
  close(FILE);
  chomp $c;
  return $c;
}

print "%package $pat\n";
my $cat = lc(read_file("toinstall/$pat/role"));
$cat =~ s, ,,g;
print "%pattern_$cat\n";

my $summaries = {
	'32bit' => '32-Bit Runtime Environment',
	'64bit' => '64-Bit Runtime Environment',
	'apparmor' => 'AppArmor',
	'apparmor_opt' => 'AppArmor',
	'base' => 'Base System',
	'Basis-Devel' => 'C/C++ Compiler and Tools',
	'books' => 'Documentation',
	'ccb' => 'Common Code Base (for certification)',
	'console' => 'Console Tools',
	'default' => 'Default System',
	'desktop-base' => 'Desktop Base System',
	'desktop-gnome' => 'GNOME (Default)',
	'desktop-gnome-devel' => 'GNOME Development',
	'desktop-gnome-laptop' => 'GNOME Laptop',
	'desktop-kde' => 'KDE',
	'desktop-kde-devel' => 'KDE Development',
	'desktop-kde-laptop' => 'KDE Laptop',
	'devel_basis' => 'Base Development',
	'devel_C_C++' => 'C/C++ Development',
	'devel_cell' => 'Cell Development',
	'devel_gnome' => 'GNOME Development',
	'devel_ide' => 'Integrated Development Environments',
	'devel_java' => 'Java Development',
	'devel_kde' => 'KDE Development',
	'devel_kernel' => 'Linux Kernel Development',
	'devel_mono' => '.NET Development',
	'devel_perl' => 'Perl Development',
	'devel_python' => 'Python Development',
	'devel_qt4' => 'Qt 4 Development',
	'devel_rails' => 'Ruby on Rails Development',
	'devel_rpm_build' => 'RPM Build Environment',
	'devel_ruby' => 'Ruby Development',
	'devel_tcl' => 'Tcl/Tk Development',
	'devel_web' => 'Web Development',
	'devel_yast' => 'YaST Development',
	'dhcp_dns_server' => 'DHCP and DNS Server',
	'directory_server' => 'Directory Server (LDAP)',
	'documentation' => 'Help and Support Documentation',
	'Dom0' => 'Virtualization Host (non-embedded)',
	'e17' => 'Enlightment',
	'enhanced_base' => 'Enhanced Base System',
	'enhanced_base_opt' => 'Enhanced Base System',
	'file_server' => 'File Server',
	'fonts' => 'Fonts',
	'fonts_opt' => 'Fonts',
	'games' => 'Games',
	'games_opt' => 'Games',
	'gateway_server' => 'Internet Gateway',
	'gnome' => 'GNOME Desktop Environment',
	'gnome_admin' => 'GNOME Administration Tools',
	'gnome_basis' => 'GNOME Base System',
	'gnome_basis_opt' => 'GNOME Base System',
	'gnome_games' => 'GNOME Games',
	'gnome_ide' => 'GNOME Integrated Development Environment',
	'gnome_imaging' => 'GNOME Graphics',
	'gnome_imaging_opt' => 'GNOME Graphics',
	'gnome_internet' => 'GNOME Internet',
	'gnome_laptop' => 'GNOME Laptop',
	'gnome_multimedia' => 'GNOME Multimedia',
	'gnome_multimedia_opt' => 'GNOME Multimedia',
	'gnome_office' => 'GNOME Office',
	'gnome_office_opt' => 'GNOME Office',
	'gnome_utilities' => 'GNOME Utilities',
	'gnome_utilities_opt' => 'GNOME Utilities',
	'gnome_xgl' => 'GNOME Desktop Effects',
	'gnome_yast' => 'YaST GNOME User Interfaces',
	'ha_sles' => 'High Availability',
	'imaging' => 'Graphics',
	'imaging_opt' => 'Graphics',
	'jeos' => 'Just Enough Operating System',
	'kde' => 'KDE Desktop Environment',
	'kde4' => 'KDE4 Desktop Environment',
	'kde4_admin' => 'KDE4 Administration Tools',
	'kde4_basis' => 'KDE4 Base System',
	'kde4_basis_opt' => 'KDE4 Base System',
	'kde4_edutainment' => 'KDE4 Education',
	'kde4_games' => 'KDE4 Games',
	'kde4_games_opt' => 'KDE4 Games',
	'kde4_help' => 'KDE4 Help System',
	'kde4_ide' => 'KDE4 Integrated Development Environment',
	'kde4_imaging' => 'KDE Graphics',
	'kde4_imaging_opt' => 'KDE Graphics',
	'kde4_internet' => 'KDE Internet',
	'kde4_laptop' => 'KDE Laptop',
	'kde4_multimedia' => 'KDE Multimedia',
	'kde4_office' => 'KDE Office',
	'kde4_office_opt' => 'KDE Office',
	'kde4_pure' => 'KDE System',
	'kde4_system' => 'KDE System',
	'kde4_utilities' => 'KDE Utilities',
	'kde4_utilities_opt' => 'KDE Utilities',
	'kde4_xgl' => 'KDE Desktop Effects',
	'kde4_yast' => 'YaST KDE User Interfaces',
	'kde_admin' => 'KDE Administration Tools',
	'kde_basis' => 'KDE Base System',
	'kde_basis_opt' => 'KDE Base System',
	'kde_edutainment' => 'KDE Edutainment',
	'kde_games' => 'KDE Games',
	'kde_games_opt' => 'KDE Games',
	'kde_help' => 'KDE Help System',
	'kde_ide' => 'KDE Integrated Development Environment',
	'kde_imaging' => 'KDE Graphics',
	'kde_imaging_opt' => 'KDE Graphics',
	'kde_internet' => 'KDE Internet',
	'kde_laptop' => 'KDE Laptop',
	'kde_multimedia' => 'KDE Multimedia',
	'kde_office' => 'KDE Office',
	'kde_office_opt' => 'KDE Office',
	'kde_system' => 'KDE System',
	'kde_utilities' => 'KDE Utilities',
	'kde_utilities_opt' => 'KDE Utilities',
	'kde_xgl' => 'KDE Desktop Effects',
	'kde_yast' => 'YaST KDE User Interfaces',
	'kernel-devel' => 'Kernel Development',
	'kvm_server' => 'KVM Host Server',
	'lamp_server' => 'Web and LAMP Server',
	'laptop' => 'Laptop',
	'lxde' => 'LXDE Desktop Environment',
	'lxde_laptop' => 'LXDE Laptop',
	'lxde_office' => 'LXDE Office',
	'mail_server' => 'Mail and News Server',
	'Minimal' => 'Minimal System (Appliances)',
	'minimal_base' => 'Base System',
	'minimal_base-conflicts' => 'Base System',
	'misc_server' => 'Miscellaneous Server',
	'moblin' => 'Moblin User eXperience',
	'MOBLIN' => 'SUSE Moblin',
	'mono' => 'Mono Development',
	'multimedia' => 'Multimedia',
	'multimedia_opt' => 'Multimedia',
	'network_admin' => 'Network Administration',
	'non_oss' => 'Misc. Proprietary Packages',
	'non_oss_java' => 'Java Environment',
	'non_oss_opt' => 'Misc. Proprietary Packages',
	'novell-ncl' => 'Novell Client for Linux',
	'Novell-software' => 'Novell Applications',
	'ofed' => 'Infiniband (OFED)',
	'office' => 'Office Software',
	'office_opt' => 'Office Software',
	'oracle_server' => 'Oracle Server Base',
	'print_server' => 'Print Server',
	'remote_desktop' => 'Remote Desktop',
	'rest_cd_gnome' => 'Remaining Software',
	'rest_cd_kde4' => 'Remaining Software',
	'rest_cd_x11' => 'Remaining Software',
	'rest_core_dvd' => 'Remaining Software',
	'rest_dvd' => 'Remaining Software',
	'rest_dvd9' => 'Remaining Software',
	'rest_promo_dvd' => 'Remaining Software',
	'rest_sdk' => 'Remaining Software',
	'rest_sled' => 'Remaining Software',
	'rest_sled_live' => 'Remaining Software',
	'rest_sles' => 'Remaining Software',
	'sap_server' => 'SAP Application Server Base',
	'sdk_basis' => 'SDK: Base Development',
	'sdk_c_c++' => 'SDK: C/C++ Development',
	'sdk_cell' => 'SDK: Cell Development',
	'sdk_certification' => 'SDK: Certification',
	'sdk_doc' => 'SDK: Documentation Tools',
	'sdk_gnome' => 'SDK: GNOME Development',
	'sdk_java' => 'SDK: Java Development',
	'sdk_kde' => 'SDK: KDE Development',
	'sdk_kernel' => 'SDK: Linux Kernel Development',
	'sdk_libs' => 'SDK: Programming Libraries',
	'sdk_mono' => 'SDK: .NET Development',
	'sdk_other' => 'SDK: Miscellaneous',
	'sdk_perl' => 'SDK: Perl Development',
	'sdk_python' => 'SDK: Python Development',
	'sdk_qt4' => 'SDK: Qt 4 Development',
	'sdk_rails' => 'SDK: Ruby on Rails Development',
	'sdk_ruby' => 'SDK: Ruby Development',
	'sdk_versioning' => 'SDK: Version Control Systems',
	'sdk_web' => 'SDK: Web Development',
	'sdk_yast' => 'SDK: YaST Development',
	'sle_rt' => 'Real Time',
	'SLMS' => 'SLMS: Management Server',
	'SLMS-Ext' => 'SLMS: Customer Service',
	'SMT' => 'Subscription Management Tool',
	'sw_management' => 'Software Management',
	'sw_management_gnome' => 'Package Management - Graphical Tools for GNOME',
	'sw_management_kde' => 'Package Management - Graphical Tools for KDE',
	'sw_management_kde4' => 'Package Management - Graphical Tools for KDE',
	'tabletpc' => 'TabletPC',
	'technical_writing' => 'Technical Writing',
	'update_test' => 'Tests for the Update Stack',
	'voip' => 'Voice Over IP Clients',
	'voip_server' => 'Voice Over IP Server',
	'WBEM' => 'Web-Based Enterprise Management',
	'webyast' => 'WebYaST',
	'WebYaST-Service' => 'WebYaST: REST service components',
	'webyast-ui' => 'WebYaST: User interface components',
	'WebYaST-UI' => 'WebYaST: User interface components',
	'webyast-ws' => 'WebYaST: REST service components',
	'x11' => 'X Window System',
	'x11_opt' => 'X Window System',
	'x11_yast' => 'YaST User Interfaces',
	'x86' => 'x86 Runtime Environment',
	'xen_server' => 'Xen Virtual Machine Host Server',
	'xfce' => 'XFCE Desktop Environment',
	'xfce_basis' => 'XFCE Base System',
	'xfce_laptop' => 'XFCE Laptop',
	'xfce_office' => 'XFCE Office',
	'yast2_basis' => 'YaST System Administration',
	'yast2_install_wf' => 'YaST Installation Packages'
};
print "Summary:        " . ($summaries->{$pat} || $pat) . "\n";
print "Group:          Metapackages\n";
print "Provides:       pattern() = $pat\n";
print "Provides:       pattern-icon() = " . uri_escape(read_file("toinstall/$pat/icon")) . "\n";
print "Provides:       pattern-order() = " . uri_escape(read_file("toinstall/$pat/order")) . "\n";

if (read_file("toinstall/$pat/visibible") eq 'true') {
  print "Provides:       pattern-visible()\n";
}
my $ext = read_file("toinstall/$pat/extends");
if ($ext) {
  print "Provides:       pattern-extends() = " . uri_escape($ext) . "\n";
}

my $supplements = read_file("toinstall/$pat/supplements");
my $freshens = read_file("toinstall/$pat/freshens");
if ($supplements) {
  if ($freshens) {
    print "Supplements:    packageand(patterns-$product-$freshens:patterns-$product-$supplements)\n";
  } else {
    print "Supplements:    patterns-$product-$supplements\n";
  }
}

open(REQ, "toinstall/$pat/requires");
while ( <REQ> ) {
  chomp;
  print "Requires:       pattern() = $_\n";
}
close(REQ);

open(REQ, "toinstall/$pat/recommends");
while ( <REQ> ) {
  chomp;
  print "Recommends:     pattern() = $_\n";
}
close(REQ);

open(REQ, "toinstall/$pat/provides");
while ( <REQ> ) {
  chomp;
  print "Provides:       pattern() = $_\n";
}
close(REQ);

open(REQ, "toinstall/$pat/obsoletes");
while ( <REQ> ) {
  chomp;
  print "Obsoletes:      pattern() = $_\n";
}
close(REQ);

open(REQ, "toinstall/$pat/conflicts");
while ( <REQ> ) {
  chomp;
  print "Conflicts:       pattern() = $_\n";
}
close(REQ);

open(REQ, "toinstall/$pat/suggests");
while ( <REQ> ) {
  chomp;
  print "Suggests:       pattern() = $_\n";
}
close(REQ);

open(REQ, "toinstall/$pat/sel");
while ( <REQ> ) {
  chomp;
  translate_sel("data/$_", $pat);
}
close(REQ);

print "\n";

print "%description $pat\n";
open(SUM, "utf8_description/$pat/default");
while ( <SUM> ) {
  chomp;
  next if ($_ eq '+Des:' || $_ eq '-Des:');
  print "$_\n";
}
print "\n";

print "%files $pat\n";
#print "%defattr(-,root,root)\n";
print "/usr/share/doc/packages/patterns-$pat\n";
print "\n";

